[package]
name = "repo-state"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
git-process = { path = "../git-process" }
tokio.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
futures.workspace = true

[dev-dependencies]
tempfile = "3"
